server:
  port: 8080

spring:
  application:
    name: aim-backend
  datasource:
    url: jdbc:mysql://localhost:3306/aimdb
    username: root
    password: Unlock76!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    com.aim: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# API Configuration
app:
  api:
    # Set to false to use real Amadeus API (requires valid credentials)
    # Amadeus API credentials (get from https://developers.amadeus.com/)
    amadeus-client-id: zJrXK9OMeWAq1ZBYUuqghhm30wzAeuKl
    amadeus-client-secret: o0DGIm8mXHEhASJm
    # Use 'test' for test environment, 'production' for production
    amadeus-environment: test
    amadeus-base-url: https://test.api.amadeus.com/v2

# Stripe Configuration
stripe:
  secret:
    key: sk_test_51Rr6S8EMe6uiUy78O7Ui3bsB5uL37u5EaT36D3EoMjMLL9oeaOt0demOyJTKdwExrqGKF1pLAVIPmA3GirtRSTbj00vPxd2pZ7
  publishable:
    key: pk_test_51Rr6S8EMe6uiUy78qMaiP1chYDylNOyep9BQmvgUHIwdX68bD7SzP3alZmktorGUXIBKUaZ7wFswYiKS9TLwkF6900PGNBBdbt
