server:
  port: 8080

spring:
  application:
    name: aim-backend
  datasource:
    url: jdbc:mysql://localhost:3306/aimdb
    username: root
    password: Unlock76!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

logging:
  level:
    com.aim: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# API Configuration
app:
  api:
    # Set to false to use real Amadeus API (requires valid credentials)
    use-mock-data: false
    # Amadeus API credentials (get from https://developers.amadeus.com/)
    amadeus-client-id: a0iahRmoeamxMNGcKodHc1Yp2PYjTwGd
    amadeus-client-secret: TouHvCEZsMQQz1vA
    amadeus-base-url: https://test.api.amadeus.com/v2
